# Site information
site_name: "Cinéphile: Top Films For All"
# site_url: 
# site_author:
site_description: "Top movie collections"
# copyright:
# repo_name: 
# repo_url: 

# Theme
theme:
  name: material
  language: "zh"

# MORE-NAV
nav:
  - 首页:
      - index.md
