name: GitHub Pages

on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "30 23 * * 3,6"
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      REPO_NAME: ${{ secrets.REPO_MOVIES }}
      SRC_NAME: source

    steps:
      - uses: actions/checkout@v4

      - name: Checkout doc repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.REPO_NAME }}
          token: ${{ secrets.GH_TOKEN_ACCESS }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Build Site
        run: |
          BASE=${{ env.SRC_NAME }}
          SITE="https://${{ env.USER }}.github.io/${{ env.REPO }}/"
          echo $BASE $SITE
          bash $BASE/deploy.sh $BASE $SITE

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
